/*
 * autorevision.h - Generated version info for webOS build
 * This file is normally generated by the autorevision tool
 */

#ifndef AUTOREVISION_H
#define AUTOREVISION_H

#define SVN_REV 0
#define SVN_LOW_REV 0
#define SVN_REV_STR "0"
#define SVN_LOW_REV_STR "0"
#define SVN_SHORT_HASH "webos"
#define SVN_URI "2.3-webos"

#ifdef SVN_AUTOREVISION_STATIC
SVN_AUTOREVISION_STATIC const char svn_uri_cstr[] = SVN_URI;
#endif

#endif /* AUTOREVISION_H */
